### ISSUE TITLE
galaxy docker deletes custom tools in export directory

### ISSUE THREAD

**Issue by enuggetry** [bgruening/docker-galaxy-blast#3]
I'm having problems adding custom tools to a docker galaxy instance export directory. Using galaxy docker https://github.com/bgruening/docker-galaxy-blast with **export** option.

Using the invocation: 
`docker run -d -p 8080:80 -v /home/user/galaxy_storage/:/export/ bgruening/galaxy-blast
`
1) i tried adding my tools into the galaxy_storage/galaxy-central/tools directory (galaxy-central/tools/mytools). And I put my tool_conf.xml in galaxy-central/config. But, galaxy-central/tools/mytools directory gets deleted every time I start docker galaxy.

2) then I put my tool defs under galaxy-central (galaxy-central/mytools), trying relative and absolute paths in config/tool_conf.xml in section. None of these seem to work. My tools don't show up in the sidebar.

```
<toolbox>
  <section id="MyTools" name="My Tools">
    <tool file="/var/www/galaxy_storage/galaxy-central/mytools/mytooldef_a.xml" />
    <tool file="../mytools/mytooldef_b.xml" />
  </section>
</toolbox>

```

How can I get this working with the docker instance with export directory? Thanks.

**Comment by bgruening** [comment]
Please make sure you copy your tools into `/home/user/galaxy_storage/`. Inside the container they should be under `/export` not under `/galaxy-central/`.

Moreover, your tool_conf.xml should look like this.

```
<toolbox>
  <section id="MyTools" name="My Tools">
    <tool file="/export/galaxy-central/mytools/mytooldef_a.xml" />
  </section>
</toolbox>
```

For more information please see: https://github.com/bgruening/docker-galaxy-stable/blob/master/README.md#Integrating-non-Tool-Shed-tools-into-the-container

Hope you enjoy Galaxy!

**Comment by enuggetry** [comment]
Thanks.  That clears it up.

**Comment by bgruening** [comment]
@enuggetry I also updated the image here.

**Comment by enuggetry** [comment]
It might also be helpful to note that with the addition of the custom /local_tools, in the example, noting the reference to **config/tool_conf.xml.sample** on the `docker run` command:
`-e GALAXY_CONFIG_TOOL_CONFIG_FILE=config/tool_conf.xml.sample,config/shed_tool_conf.xml.sample,/local_tools/my_tools.xml`

we should change
`<toolbox tool_path="../shed_tools">` to `<toolbox tool_path="/local_tools/shed_tools">`
to ensure the shed tools will show up.  Otherwise, the BLAST+ tools don't show up.  This bit might help to clarify things too.
